---
permalink: task-download-the-open-virtual-appliance.html 
sidebar: sidebar 
keywords: download, open virtual appliance 
summary: 'Laden Sie die Open Virtual Appliance (OVA) in VMware vCenter 8.0 und höher herunter, um BlueXP Backup- und Recovery-Lösungen für VMs zu implementieren.' 
---
= Laden Sie die Open Virtual Appliance herunter
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Laden Sie die Open Virtual Appliance (OVA) in VMware vCenter 8.0 und höher herunter, um BlueXP Backup- und Recovery-Lösungen für VMs zu implementieren.

.Bevor Sie beginnen
Wenn die vom Entrust-Zertifikat signierte OVA nicht vertrauenswürdig ist, stellen Sie sicher, dass Sie Zwischenzertifikate installieren und dem vCenter hinzufügen.

.Schritte
. BlueXP Backup und Recovery für VMs OVA herunterladen:
+
.. Melden Sie sich bei an https://mysupport.netapp.com/products/index.html["NetApp Support Website"^]
.. Wählen Sie aus der Liste der Produkte *BlueXP Backup und Recovery für VMs* aus und klicken Sie dann auf die Schaltfläche *Neueste Version herunterladen*.
.. Laden Sie BlueXP Backup und Recovery für VMs herunter `.tar` Datei an jedem Speicherort.


. Extrahieren Sie den Inhalt der tar-Datei. Die tar-Datei enthält den Ordner OVA und certs. Der Zertifikatordner enthält Zwischenzertifikate.
. Navigieren Sie im vSphere-Client zu *Administration > Zertifikate > Zertifikatverwaltung*.
. Klicken Sie neben *Trusted Root Certificates* auf *Add*.
+

NOTE: Standardmäßig ist das Stammzertifikat installiert.

+
.. Wechseln Sie zum Ordner certs.
.. Wählen Sie die Zwischenzertifikate aus.
.. Installieren Sie jedes Zertifikat einzeln.


. Die Zertifikate werden einem Panel unter Vertrauenswürdige Stammzertifikate hinzugefügt.
+
Sobald die Zertifikate installiert sind, kann OVA überprüft und bereitgestellt werden.



[NOTE]
====
Wenn die heruntergeladene OVA nicht manipuliert wird, wird in der Spalte Publisher das vertrauenswürdige Zertifikat angezeigt.

====